{% set name = "coded-flows" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/coded_flows-{{ version }}.tar.gz
  sha256: f51890db26e3cfbc25858e8982317f56b2c231ee2b73ff98e38f04d007672a04

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.9.0,<4.0.0
    - pandas >=2.1.0,<3.0.0
    - pyarrow >=14.0.2,<15.0.0
    - pydantic >=2.6.4,<3.0.0
    - email-validator >=2.0.0,<3.0.0
    - pycountry >=22.3.5,<23.0.0
    - pillow >=10.1.0,<11.0.0
    - pydantic-extra-types >=2.6.0,<3.0.0

test:
  imports:
    - coded_flows
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/color-coded-codes/coded-flows
  summary: Various utilities for Coded Flows
  license: 'MIT'
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aminelemaizi
