{% set name = "coded-flows" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/coded_flows-{{ version }}.tar.gz
  sha256: 498c03af2430030231b3626d820c4c70cdf1cb7ca6a1f0222cb648855c279a4d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.9.0,<4.0.0
    - pandas >=2.1.0,<3.0.0
    - pyarrow >=16.0.0,<17.0.0
    - pydantic >=2.6.4,<3.0.0
    - email-validator >=2.0.0,<3.0.0
    - pycountry >=24.6.1,<24.0.0
    - pillow >=10.1.0,<11.0.0
    - pydantic-extra-types >=2.6.0,<3.0.0

test:
  imports:
    - coded_flows
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/color-coded-codes/coded-flows
  summary: Various utilities for Coded Flows
  license: 'MIT'
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aminelemaizi
