{% set name = "coded-flows" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/coded_flows-{{ version }}.tar.gz
  sha256: b2d9f7fc7b27b7f0284a669daf751544887574cb625f7432d1798c45ff5ca91b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - pandas >=2.1.0,<3.0.0
    - pyarrow >=16.0.0,<17.0.0
    - pydantic >=2.6.4,<3.0.0
    - email-validator >=2.0.0,<3.0.0
    - pycountry >=24.6.1,<25.0.0
    - pillow >=10.1.0,<11.0.0
    - pydantic-extra-types >=2.6.0,<3.0.0

test:
  imports:
    - coded_flows
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/color-coded-codes/coded-flows
  summary: Various utilities for Coded Flows
  license: 'MIT'
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aminelemaizi
